#!/bin/bash
# Copyright 2011 Benjamin Fleischer

readonly SUDO="/usr/bin/sudo"
readonly INSTALLER="/usr/sbin/installer"

readonly SYSTEM_ROOT="$4"

"$SUDO" "$INSTALLER" -dumplog -pkg "OSXFUSE.pkg" -target "$SYSTEM_ROOT"
exit $?
