#!/bin/sh
#
# Copyright (C) 2006 Google. All Rights Reserved.
#
PACKAGE_PATH=$1
INSTALL_PATH=$2
INSTALL_VOLUME=$3
SYSTEM_ROOT=$4

## OSXFUSE User Library

# Remove any incompatible versions of libfuse we might have installed.
/bin/rm -f "$INSTALL_VOLUME"/usr/local/lib/libosxfuse.*
/bin/rm -f "$INSTALL_VOLUME"/usr/local/lib/pkgconfig/osxfuse.pc

## Signal success

exit 0
